const DATA_URL='../sample-data/banana-farms.geojson';
let features=[]; let map;
const el=id=>document.getElementById(id);
function fmt(n){return new Intl.NumberFormat('th-TH',{maximumFractionDigits:1}).format(n)}
function boundsOf(fs){let b=new maplibregl.LngLatBounds();fs.forEach(f=>f.geometry.coordinates[0].forEach(c=>b.extend(c)));return b}
function renderList(fs){el('farmList').innerHTML=fs.map(f=>{const p=f.properties;return `<div class="farm" data-id="${p.farm_id}"><strong>🍌 ${p.farm_id}</strong><small>${p.province} · ${p.amphoe} · ${p.tambon}</small><br><small>${fmt(p.area_rai)} ไร่ · ${p.status}</small></div>`}).join('');document.querySelectorAll('.farm').forEach(x=>x.onclick=()=>{const f=features.find(z=>z.properties.farm_id===x.dataset.id);map.fitBounds(boundsOf([f]),{padding:100,maxZoom:15})})}
function update(fs){el('farmCount').textContent=fmt(fs.length);el('areaTotal').textContent=fmt(fs.reduce((s,f)=>s+(+f.properties.area_rai||0),0));el('provinceCount').textContent=new Set(fs.map(f=>f.properties.province)).size;renderList(fs);if(map.getSource('farms'))map.getSource('farms').setData({type:'FeatureCollection',features:fs})}
async function init(){const r=await fetch(DATA_URL);const geo=await r.json();features=geo.features;const provinces=[...new Set(features.map(f=>f.properties.province))];provinces.forEach(p=>{const o=document.createElement('option');o.value=p;o.textContent=p;el('provinceFilter').appendChild(o)});map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[100,8.4],zoom:9});map.addControl(new maplibregl.NavigationControl());map.on('load',()=>{map.addSource('farms',{type:'geojson',data:geo});map.addLayer({id:'farms-fill',type:'fill',source:'farms',paint:{'fill-opacity':.38}});map.addLayer({id:'farms-line',type:'line',source:'farms',paint:{'line-width':2}});map.on('click','farms-fill',e=>{const p=e.features[0].properties;new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<b>🍌 ${p.farm_id}</b><br>${p.province} / ${p.amphoe} / ${p.tambon}<br>พื้นที่ ${fmt(+p.area_rai)} ไร่`).addTo(map)});update(features);map.fitBounds(boundsOf(features),{padding:80,maxZoom:12})});el('provinceFilter').onchange=e=>update(e.target.value?features.filter(f=>f.properties.province===e.target.value):features);el('fitBtn').onclick=()=>map.fitBounds(boundsOf(features),{padding:80,maxZoom:12})}
init().catch(e=>{console.error(e);el('farmList').innerHTML='<p>ไม่สามารถโหลดข้อมูลแปลงได้</p>'});
