const DATA_URL='../sample-data/banana-farms.geojson';
let features=[];let map;let selectedPoint=null;
const el=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:1}).format(n);
function boundsOf(fs){const b=new maplibregl.LngLatBounds();fs.forEach(f=>f.geometry.coordinates[0].forEach(c=>b.extend(c)));return b}
function renderList(fs){el('farmList').innerHTML=fs.map(f=>{const p=f.properties;return `<div class="farm" data-id="${p.farm_id}"><strong>🍌 ${p.farm_id}</strong><small>${p.province||'ไม่ระบุ'} · ${p.amphoe||''} · ${p.tambon||''}</small><br><small>${fmt(+p.area_rai||0)} ไร่ · ${p.status||'draft'}</small></div>`}).join('')||'<p>ไม่พบแปลง</p>';document.querySelectorAll('.farm').forEach(x=>x.onclick=()=>{const f=features.find(z=>z.properties.farm_id===x.dataset.id);map.fitBounds(boundsOf([f]),{padding:100,maxZoom:15})})}
function update(fs){el('farmCount').textContent=fmt(fs.length);el('areaTotal').textContent=fmt(fs.reduce((s,f)=>s+(+f.properties.area_rai||0),0));el('provinceCount').textContent=new Set(fs.map(f=>f.properties.province).filter(Boolean)).size;renderList(fs);if(map.getSource('farms'))map.getSource('farms').setData({type:'FeatureCollection',features:fs})}
function openForm(){el('farmForm').reset();el('coordinates').value=selectedPoint?`${selectedPoint[1].toFixed(6)}, ${selectedPoint[0].toFixed(6)}`:'';el('formMsg').textContent='';el('farmDialog').showModal()}
function setPoint(c){selectedPoint=c;el('coordinates').value=`${c[1].toFixed(6)}, ${c[0].toFixed(6)}`;new maplibregl.Popup().setLngLat(c).setHTML('<b>📍 จุดแปลงใหม่</b><br>กด “บันทึก” เพื่อสร้างข้อมูลตัวอย่าง').addTo(map)}
function saveFarm(){if(!selectedPoint){el('formMsg').textContent='กรุณาใช้ GPS หรือคลิกตำแหน่งบนแผนที่';return}const p={farm_id:el('farm_id').value.trim(),grower_id:'BG-'+el('farm_id').value.trim().replace(/\D/g,'').padStart(4,'0'),province:'ไม่ระบุ',amphoe:'',tambon:'',area_rai:+el('area_rai').value||0,status:'active',grower_name:el('grower_name').value,phone:el('phone').value,variety:el('variety').value,planting_date:el('planting_date').value,plant_count:+el('plant_count').value||0};if(!p.farm_id||!p.grower_name){el('formMsg').textContent='กรุณากรอกรหัสแปลงและชื่อเกษตรกร';return}features=[...features,{type:'Feature',properties:p,geometry:{type:'Point',coordinates:selectedPoint}}];update(features);map.getSource('farms').setData({type:'FeatureCollection',features});el('farmDialog').close();map.flyTo({center:selectedPoint,zoom:15})}
async function init(){const r=await fetch(DATA_URL);const geo=await r.json();features=geo.features;const provinces=[...new Set(features.map(f=>f.properties.province).filter(Boolean))];provinces.forEach(p=>{const o=document.createElement('option');o.value=p;o.textContent=p;el('provinceFilter').appendChild(o)});map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[100,8.4],zoom:9});map.addControl(new maplibregl.NavigationControl());map.on('load',()=>{map.addSource('farms',{type:'geojson',data:geo});map.addLayer({id:'farms-fill',type:'fill',source:'farms',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-opacity':.38}});map.addLayer({id:'farms-line',type:'line',source:'farms',filter:['==',['geometry-type'],'Polygon'],paint:{'line-width':2}});map.addLayer({id:'farms-points',type:'circle',source:'farms',filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':7,'circle-stroke-width':2}});map.on('click','farms-fill',e=>{const p=e.features[0].properties;new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<b>🍌 ${p.farm_id}</b><br>${p.province||''} / ${p.amphoe||''} / ${p.tambon||''}<br>พื้นที่ ${fmt(+p.area_rai)} ไร่<br>พันธุ์ ${p.variety||'—'}`).addTo(map)});update(features);map.fitBounds(boundsOf(features),{padding:80,maxZoom:12});map.on('click',e=>{if(el('farmDialog').open)return;if(e.originalEvent.shiftKey)setPoint([e.lngLat.lng,e.lngLat.lat])})});el('provinceFilter').onchange=e=>update(e.target.value?features.filter(f=>f.properties.province===e.target.value):features);el('fitBtn').onclick=()=>map.fitBounds(boundsOf(features),{padding:80,maxZoom:12});el('addBtn').onclick=openForm;el('gpsBtn').onclick=()=>{if(!navigator.geolocation){el('formMsg').textContent='อุปกรณ์ไม่รองรับ GPS';return}navigator.geolocation.getCurrentPosition(pos=>{setPoint([pos.coords.longitude,pos.coords.latitude]);map.flyTo({center:[pos.coords.longitude,pos.coords.latitude],zoom:16})},()=>el('formMsg').textContent='ไม่สามารถอ่านตำแหน่ง GPS ได้')};el('saveBtn').onclick=saveFarm}
init().catch(e=>{console.error(e);el('farmList').innerHTML='<p>ไม่สามารถโหลดข้อมูลแปลงได้</p>'});
